/**
 * TaskWidget.jsx
 *
 * Renders a workItem (task) interaction — a contact-centre task generated by a
 * backend information system (fraud alert, suspicious activity, AML review, etc.).
 *
 * Props:
 *   task        – raw taskPayload from Desktop (mediaType === "workItem")
 *   darkMode    – boolean
 *   mockMode    – boolean  (use mock data when true or no task supplied)
 *   onNavigate  – fn(view, params) for cross-tab navigation
 */

import React, { useState, useEffect, useCallback, useRef } from 'react';
import PropTypes from 'prop-types';
import { Button } from '@momentum-ui/react';
import { useI18n } from '../i18n/I18nContext';
import { getMockData } from '../mock/mockData';
import './task.css';

// ─── Helpers ───────────────────────────────────────────────────────────────

/** Extract a single CAD field value from the raw callAssociatedData map. */
const cadVal = (cad, field) => {
  if (!cad) return null;
  const v = cad[field];
  if (!v) return null;
  return typeof v === 'object' && 'value' in v ? v.value : String(v);
};

/** Format elapsed/remaining seconds as M:SS */
const fmtSec = (totalSec) => {
  const abs = Math.abs(totalSec);
  const m = Math.floor(abs / 60);
  const s = abs % 60;
  const str = `${m}:${s.toString().padStart(2, '0')}`;
  return totalSec < 0 ? `-${str}` : str;
};

/** Derive display type label from task fields */
const resolveTaskType = (task) => {
  const channel = String(task?.virtualTeamName || task?.mediaChannel || '').toLowerCase();
  const cad = task?.callAssociatedData || {};
  const taskType = cadVal(cad, 'taskType') || '';
  if (taskType) return taskType;
  if (channel.includes('fraud')) return 'Fraud Alert';
  if (channel.includes('aml')) return 'AML Review';
  if (channel.includes('kyc')) return 'KYC Review';
  if (channel.includes('card')) return 'Card Alert';
  return 'Work Item';
};

/** Derive priority from queue/channel name heuristics */
const resolvePriority = (task) => {
  const channel = String(task?.virtualTeamName || task?.mediaChannel || '').toLowerCase();
  if (channel.includes('critical') || channel.includes('fraud')) return 'critical';
  if (channel.includes('high') || channel.includes('aml')) return 'high';
  if (channel.includes('low')) return 'low';
  return 'medium';
};

/**
 * Derive a human-readable description of what the task is about
 * from the queue/channel name and CAD fields.
 */
const resolveDescription = (task, t) => {
  const cad = task?.callAssociatedData || {};
  const channel = String(task?.virtualTeamName || task?.mediaChannel || '').toLowerCase();
  const customer = cadVal(cad, 'customerName') || task?.customerName || '';
  const caseId = cadVal(cad, 'caseId') || '';

  if (channel.includes('fraud') || channel.includes('card')) {
    return t('task.descriptions.fraudAlert').replace('{customer}', customer).replace('{caseId}', caseId);
  }
  if (channel.includes('aml')) {
    return t('task.descriptions.amlReview').replace('{customer}', customer).replace('{caseId}', caseId);
  }
  if (channel.includes('kyc')) {
    return t('task.descriptions.kycReview').replace('{customer}', customer);
  }
  if (channel.includes('account')) {
    return t('task.descriptions.suspiciousAccount').replace('{customer}', customer);
  }
  return t('task.descriptions.generic').replace('{customer}', customer).replace('{queue}', task?.virtualTeamName || '');
};

// ─── SLA Timer ──────────────────────────────────────────────────────────────

const SlaTimer = ({ startTimestamp, slaSec, darkMode }) => {
  const elapsed = useRef(Math.floor((Date.now() - startTimestamp) / 1000));
  const [seconds, setSeconds] = useState(elapsed.current);

  useEffect(() => {
    const id = setInterval(() => {
      elapsed.current += 1;
      setSeconds(elapsed.current);
    }, 1000);
    return () => clearInterval(id);
  }, []);

  const remaining = slaSec ? slaSec - seconds : null;
  const timerClass = remaining === null
    ? 'task-widget__timer'
    : remaining < 0
      ? 'task-widget__timer task-widget__timer--urgent'
      : remaining < 120
        ? 'task-widget__timer task-widget__timer--warning'
        : 'task-widget__timer';

  return (
    <div className={timerClass}>
      {remaining !== null
        ? (remaining < 0 ? `+${fmtSec(Math.abs(remaining))}` : fmtSec(remaining))
        : fmtSec(seconds)}
    </div>
  );
};

// ─── Main component ──────────────────────────────────────────────────────────

const TaskWidget = ({ task, darkMode, mockMode, onNavigate }) => {
  const { t, locale } = useI18n();
  const mock = getMockData(locale);
  const isDemoMode = Boolean(mockMode) || !task;

  // Use mock task when in demo mode
  const resolvedTask = isDemoMode ? mock.task?.activeTask : task;

  const [notes, setNotes] = useState('');
  const [completed, setCompleted] = useState(false);

  // Reset state when a new real task arrives
  useEffect(() => {
    if (!isDemoMode && task) {
      setNotes('');
      setCompleted(false);
    }
  }, [task?.interactionId]); // eslint-disable-line react-hooks/exhaustive-deps

  if (!resolvedTask) {
    return (
      <div className={`task-widget${darkMode ? ' md--dark' : ''}`}>
        <div className="task-widget__empty">
          <span className="task-widget__empty-icon">☑️</span>
          <span>{t('task.noTask')}</span>
        </div>
      </div>
    );
  }

  const cad = resolvedTask.callAssociatedData || {};
  const priority = resolvePriority(resolvedTask);
  const taskType = resolveTaskType(resolvedTask);
  const description = resolveDescription(resolvedTask, t);
  const startTs = resolvedTask.timeStamp || resolvedTask.monitoringStartTime || Date.now();

  // Key CAD values
  const customerName = cadVal(cad, 'customerName') || resolvedTask.customerName || '-';
  const caseId       = cadVal(cad, 'caseId') || '-';
  const taskId       = cadVal(cad, 'taskId') || resolvedTask.interactionId || '-';
  const email        = cadVal(cad, 'email') || resolvedTask.email || '-';
  const phone        = cadVal(cad, 'phone') || cadVal(cad, 'ani') || resolvedTask.ani || '-';
  const queue        = resolvedTask.virtualTeamName || '-';
  const state        = resolvedTask.state || 'connected';

  const stateClass = `task-widget__state-badge task-widget__state-badge--${
    resolvedTask.isWrapUp ? 'wrapup' : resolvedTask.isHold ? 'hold' : 'connected'
  }`;

  const stateLabel = resolvedTask.isWrapUp
    ? t('task.state.wrapup')
    : resolvedTask.isHold
      ? t('task.state.hold')
      : t('task.state.connected');

  const handleOpenCase = useCallback(() => {
    if (caseId && caseId !== '-') onNavigate?.('cases', { highlightCaseId: caseId });
  }, [caseId, onNavigate]);

  const handleOpenHistory = useCallback(() => {
    onNavigate?.('history', {});
  }, [onNavigate]);

  return (
    <div className={`task-widget${darkMode ? ' md--dark' : ''}`}>
      {/* ── Header ── */}
      <div className="task-widget__header">
        <div className="task-widget__icon">☑️</div>
        <div className="task-widget__header-info">
          <div className="task-widget__title">{taskType} — {customerName}</div>
          <div className="task-widget__subtitle">
            <span className={`task-widget__priority-badge task-widget__priority-badge--${priority}`}>
              {t(`task.priority.${priority}`)}
            </span>
            <span className={stateClass}>{stateLabel}</span>
            {queue !== '-' && <span>{queue}</span>}
          </div>
        </div>
        <div className="task-widget__sla">
          <SlaTimer
            startTimestamp={isDemoMode ? Date.now() - mock.task?.elapsedSec * 1000 : startTs}
            slaSec={isDemoMode ? mock.task?.slaSec : null}
            darkMode={darkMode}
          />
        </div>
      </div>

      {/* ── Body ── */}
      <div className="task-widget__body">

        {/* Description */}
        <div className="task-widget__section">
          <div className="task-widget__section-title">{t('task.section.description')}</div>
          <div className="task-widget__description">{description}</div>
        </div>

        {/* Customer info */}
        <div className="task-widget__section">
          <div className="task-widget__section-title">{t('task.section.customer')}</div>
          <div className="task-widget__fields">
            <div className="task-widget__field">
              <div className="task-widget__field-label">{t('task.fields.customerName')}</div>
              <div className="task-widget__field-value">{customerName}</div>
            </div>
            <div className="task-widget__field">
              <div className="task-widget__field-label">{t('task.fields.phone')}</div>
              <div className="task-widget__field-value">{phone}</div>
            </div>
            <div className="task-widget__field task-widget__field--full">
              <div className="task-widget__field-label">{t('task.fields.email')}</div>
              <div className="task-widget__field-value">{email}</div>
            </div>
          </div>
        </div>

        {/* Task details */}
        <div className="task-widget__section">
          <div className="task-widget__section-title">{t('task.section.details')}</div>
          <div className="task-widget__fields">
            <div className="task-widget__field">
              <div className="task-widget__field-label">{t('task.fields.caseId')}</div>
              <div
                className="task-widget__field-value task-widget__field-value--mono"
                style={caseId !== '-' ? { cursor: 'pointer', color: '#0052cc' } : {}}
                onClick={caseId !== '-' ? handleOpenCase : undefined}
                role={caseId !== '-' ? 'button' : undefined}
                tabIndex={caseId !== '-' ? 0 : undefined}
                onKeyDown={caseId !== '-' ? (e) => (e.key === 'Enter' || e.key === ' ') && handleOpenCase() : undefined}
              >
                {caseId}
              </div>
            </div>
            <div className="task-widget__field">
              <div className="task-widget__field-label">{t('task.fields.type')}</div>
              <div className="task-widget__field-value">
                <span className="task-widget__type-chip">{taskType}</span>
              </div>
            </div>
            <div className="task-widget__field task-widget__field--full">
              <div className="task-widget__field-label">{t('task.fields.taskId')}</div>
              <div className="task-widget__field-value task-widget__field-value--mono">{taskId}</div>
            </div>
            <div className="task-widget__field task-widget__field--full">
              <div className="task-widget__field-label">{t('task.fields.queue')}</div>
              <div className="task-widget__field-value">{queue}</div>
            </div>
          </div>
        </div>

        {/* Agent notes */}
        {!completed && (
          <div className="task-widget__section">
            <div className="task-widget__section-title">{t('task.section.notes')}</div>
            <div className="task-widget__notes">
              <textarea
                className="task-widget__notes-textarea"
                placeholder={t('task.notesPlaceholder')}
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                aria-label={t('task.section.notes')}
              />
            </div>
          </div>
        )}

        {completed && (
          <div className="task-widget__section">
            <div style={{ padding: '12px', color: '#15803d', fontWeight: 600, fontSize: 13 }}>
              ✓ {t('task.completedMessage')}
            </div>
          </div>
        )}
      </div>

      {/* ── Footer actions ── */}
      <div className="task-widget__actions">
        <Button
          ariaLabel={t('task.actions.complete')}
          color="green"
          size={28}
          disabled={completed}
          onClick={() => setCompleted(true)}
        >
          {t('task.actions.complete')}
        </Button>
        <Button
          ariaLabel={t('task.actions.viewHistory')}
          color="none"
          size={28}
          onClick={handleOpenHistory}
        >
          {t('task.actions.viewHistory')}
        </Button>
        {caseId !== '-' && (
          <Button
            ariaLabel={t('task.actions.openCase')}
            color="none"
            size={28}
            onClick={handleOpenCase}
          >
            {t('task.actions.openCase')}
          </Button>
        )}
      </div>
    </div>
  );
};

TaskWidget.propTypes = {
  task:       PropTypes.object,
  darkMode:   PropTypes.bool,
  mockMode:   PropTypes.bool,
  onNavigate: PropTypes.func,
};
TaskWidget.defaultProps = { task: null, darkMode: false, mockMode: false, onNavigate: null };

export default TaskWidget;
